description: The 20th Workshop on Models and Evolution (ME) 2026 is a satellite event at ACM/IEEE International Conference on Model Driven Engineering Languages and Systems (MODELS 2026).
author: Wael Kessentini, Juri Di Rocco, and Djamel Eddine Khelladi.
keywords: ME, Model-Driven Engineering, Evolution, MDE, coevolution, Digital Twins

url: https://models-and-evolution.github.io
cfp-url: https://conference-hall.io/public/event/98FptSgEGcOSQZymZkUr
name: Models and Evolution

day1: Sunday 4
day2: Friday 9
month: October 2026
data-year: 2026
data-month: 10
data-day: 04
data-hour: 09

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - .gitignore
  - CNAME

navigation:
 - title: Call for Papers
   url: /call-for-paper/
 - title: Important Dates
   url: /sponsors/
 - title: Organizers
   url: /orga/
 - title: Past Editions
   url: /past-editions/
 - title: Contact
   url: /contacts/


collections:
  speakers:
    output: true
    permalink: /:collection/:name
  talks:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talks
  - scope:
      path: ""
      type: speakers
    values:
      layout: speakers
  - scope:
      path: "speakers/tbd"
    values:
      sitemap: false
  - scope:
      path: "speakers/volcamp"
    values:
      sitemap: false

syndication:
  twitter: http://www.twitter.com/models-evolution
  github: https://github.com/models-and-evolution
  linkedin: https://www.linkedin.com/company/volcampio
  youtube: https://www.youtube.com/channel/UC5iGUFHEJbSTU5wpbT6KIcw/featured

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-minifier
  - kramdown-parser-gfm

